name: lib buildington

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  BUILD_TYPE: Release
  ANDROID_ABI: arm64-v8a
  ANDROID_PLATFORM: android-21

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK (required for Android SDK)
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Download and set up Android NDK
      uses: nttld/setup-ndk@v1
      with:
        ndk-version: '25.2.9519653' # Use the version compatible with your CMake/SDK setup

    - name: Configure CMake for Android
      run: >
        cmake -S app/src/main/cpp
        -B build
        -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}
        -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_HOME/build/cmake/android.toolchain.cmake
        -DANDROID_ABI=${{ env.ANDROID_ABI }}
        -DANDROID_PLATFORM=${{ env.ANDROID_PLATFORM }}

    - name: Build
      run: cmake --build build --config ${{ env.BUILD_TYPE }}

    - name: Archive Build Output
      run: |
        mkdir -p artifacts
        cp build/libModLoader.so artifacts/

    - name: Create Release
      if: github.ref == 'refs/heads/master'
      id: create_release
      uses: actions/create-release@v1
      with:
        tag_name: v${{ github.run_number }}
        release_name: Release v${{ github.run_number }}
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload Release Asset
      if: github.ref == 'refs/heads/master'
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./artifacts/libModLoader.so
        asset_name: libModLoader.so
        asset_content_type: application/octet-stream
